name = "SortingNetworkSearch"
version = "0.1.0"
defaultTargets = ["sortingnetworksearch"]

[[lean_lib]]
name = "SortingNetworkSearch"

[[lean_exe]]
name = "sortingnetworksearch"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
